<?php

namespace Database\Seeders\InitialData;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Country::withoutEvents(function (): void {
            // alpha2, alpha3, full_name, phone_code, currency_code, currency_name
            $countries = [
                ['AF', 'AFG', 'Afghanistan', 93, 'AFN', 'Afghan Afghani'],
                ['AL', 'ALB', 'Albania', 355, 'ALL', 'Albanian Lek'],
                ['DZ', 'DZA', 'Algeria', 213, 'DZD', 'Algerian Dinar'],
                ['AS', 'ASM', 'American Samoa', 1684, 'USD', 'US Dollar'],
                ['AD', 'AND', 'Andorra', 376, 'EUR', 'Euro'],
                ['AO', 'AGO', 'Angola', 244, 'AOA', 'Angolan Kwanza'],
                ['AI', 'AIA', 'Anguilla', 1264, 'XCD', 'East Caribbean Dollar'],
                ['AQ', 'ATA', 'Antarctica', 672, NULL, NULL],
                ['AG', 'ATG', 'Antigua and Barbuda', 1268, 'XCD', 'East Caribbean Dollar'],
                ['AR', 'ARG', 'Argentina', 54, 'ARS', 'Argentine Peso'],
                ['AM', 'ARM', 'Armenia', 374, 'AMD', 'Armenian Dram'],
                ['AW', 'ABW', 'Aruba', 297, 'AWG', 'Aruban Florin'],
                ['AU', 'AUS', 'Australia', 61, 'AUD', 'Australian Dollar'],
                ['AT', 'AUT', 'Austria', 43, 'EUR', 'Euro'],
                ['AZ', 'AZE', 'Azerbaijan', 994, 'AZN', 'Azerbaijani Manat'],
                ['BS', 'BHS', 'Bahamas', 1242, 'BSD', 'Bahamian Dollar'],
                ['BH', 'BHR', 'Bahrain', 973, 'BHD', 'Bahraini Dinar'],
                ['BD', 'BGD', 'Bangladesh', 880, 'BDT', 'Bangladeshi Taka'],
                ['BB', 'BRB', 'Barbados', 1246, 'BBD', 'Barbadian Dollar'],
                ['BY', 'BLR', 'Belarus', 375, 'BYR', 'Belarusian Ruble'],
                ['BE', 'BEL', 'Belgium', 32, 'EUR', 'Euro'],
                ['BZ', 'BLZ', 'Belize', 501, 'BZD', 'Belize Dollar'],
                ['BJ', 'BEN', 'Benin', 229, 'XOF', 'CFA Franc BCEAO'],
                ['BM', 'BMU', 'Bermuda', 1441, 'BMD', 'Bermudan Dollar'],
                ['BT', 'BTN', 'Bhutan', 975, 'INR', 'Indian Rupee'],
                ['BO', 'BOL', 'Bolivia', 591, 'BOB', 'Bolivian Boliviano'],
                ['BA', 'BIH', 'Bosnia and Herzegovina', 387, 'BAM', 'Bosnia-Herzegovina Convertible Mark'],
                ['BW', 'BWA', 'Botswana', 267, 'BWP', 'Botswanan Pula'],
                ['BV', 'BVT', 'Bouvet Island', 47, 'NOK', 'Norwegian Krone'],
                ['BR', 'BRA', 'Brazil', 55, 'BRL', 'Brazilian Real'],
                ['IO', 'IOT', 'British Indian Ocean Territory', 246, 'USD', 'US Dollar'],
                ['BN', 'BRN', 'Brunei Darussalam', 673, 'BND', 'Brunei Dollar'],
                ['BG', 'BGR', 'Bulgaria', 359, 'BGN', 'Bulgarian Lev'],
                ['BF', 'BFA', 'Burkina Faso', 226, 'XOF', 'CFA Franc BCEAO'],
                ['BI', 'BDI', 'Burundi', 257, 'BIF', 'Burundian Franc'],
                ['KH', 'KHM', 'Cambodia', 855, 'KHR', 'Cambodian Riel'],
                ['CM', 'CMR', 'Cameroon', 237, 'XAF', 'CFA Franc BEAC'],
                ['CA', 'CAN', 'Canada', 1, 'CAD', 'Canadian Dollar'],
                ['CV', 'CPV', 'Cape Verde', 238, 'CVE', 'Cape Verdean Escudo'],
                ['KY', 'CYM', 'Cayman Islands', 1345, 'KYD', 'Cayman Islands Dollar'],
                ['CF', 'CAF', 'Central African Republic', 236, 'XAF', 'CFA Franc BEAC'],
                ['TD', 'TCD', 'Chad', 235, 'XAF', 'CFA Franc BEAC'],
                ['CL', 'CHL', 'Chile', 56, 'CLP', 'Chilean Peso'],
                ['CN', 'CHN', 'China', 86, 'CNY', 'Chinese Yuan'],
                ['CX', 'CXR', 'Christmas Island', 61, 'AUD', 'Australian Dollar'],
                ['CC', 'CCK', 'Cocos [Islands', 672, 'AUD', 'Australian Dollar'],
                ['CO', 'COL', 'Colombia', 57, 'COP', 'Colombian Peso'],
                ['KM', 'COM', 'Comoros', 269, 'KMF', 'Comorian Franc'],
                ['CG', 'COG', 'Congo', 242, 'XAF', 'CFA Franc BEAC'],
                ['CD', 'COD', 'Congo, the Democratic Republic of the', 242, 'CDF', 'Congolese Franc'],
                ['CK', 'COK', 'Cook Islands', 682, 'NZD', 'New Zealand Dollar'],
                ['CR', 'CRI', 'Costa Rica', 506, 'CRC', 'Costa Rican Colón'],
                ['CI', 'CIV', 'Cote D\'Ivoire', 225, 'XOF', 'CFA Franc BCEAO'],
                ['HR', 'HRV', 'Croatia', 385, 'HRK', 'Croatian Kuna'],
                ['CU', 'CUB', 'Cuba', 53, 'CUP', 'Cuban Peso'],
                ['CY', 'CYP', 'Cyprus', 357, 'EUR', 'Euro'],
                ['CZ', 'CZE', 'Czech Republic', 420, 'CZK', 'Czech Republic Koruna'],
                ['DK', 'DNK', 'Denmark', 45, 'DKK', 'Danish Krone'],
                ['DJ', 'DJI', 'Djibouti', 253, 'DJF', 'Djiboutian Franc'],
                ['DM', 'DMA', 'Dominica', 1767, 'XCD', 'East Caribbean Dollar'],
                ['DO', 'DOM', 'Dominican Republic', 1809, 'DOP', 'Dominican Peso'],
                ['EC', 'ECU', 'Ecuador', 593, 'USD', 'US Dollar'],
                ['EG', 'EGY', 'Egypt', 20, 'EGP', 'Egyptian Pound'],
                ['SV', 'SLV', 'El Salvador', 503, 'USD', 'US Dollar'],
                ['GQ', 'GNQ', 'Equatorial Guinea', 240, 'XAF', 'CFA Franc BEAC'],
                ['ER', 'ERI', 'Eritrea', 291, 'ERN', 'Eritrean Nakfa'],
                ['EE', 'EST', 'Estonia', 372, 'EUR', 'Euro'],
                ['ET', 'ETH', 'Ethiopia', 251, 'ETB', 'Ethiopian Birr'],
                ['FK', 'FLK', 'Falkland Islands', 500, 'FKP', 'Falkland Islands Pound'],
                ['FO', 'FRO', 'Faroe Islands', 298, 'DKK', 'Danish Krone'],
                ['FJ', 'FJI', 'Fiji', 679, 'FJD', 'Fijian Dollar'],
                ['FI', 'FIN', 'Finland', 358, 'EUR', 'Euro'],
                ['FR', 'FRA', 'France', 33, 'EUR', 'Euro'],
                ['GF', 'GUF', 'French Guiana', 594, 'EUR', 'Euro'],
                ['PF', 'PYF', 'French Polynesia', 689, 'XPF', 'CFP Franc'],
                ['TF', 'ATF', 'French Southern Territories', 262, 'EUR', 'Euro'],
                ['GA', 'GAB', 'Gabon', 241, 'XAF', 'CFA Franc BEAC'],
                ['GM', 'GMB', 'Gambia', 220, 'GMD', 'Gambian Dalasi'],
                ['GE', 'GEO', 'Georgia', 995, 'GEL', 'Georgian Lari'],
                ['DE', 'DEU', 'Germany', 49, 'EUR', 'Euro'],
                ['GH', 'GHA', 'Ghana', 233, 'GHS', 'Ghanaian Cedi'],
                ['GI', 'GIB', 'Gibraltar', 350, 'GIP', 'Gibraltar Pound'],
                ['GR', 'GRC', 'Greece', 30, 'EUR', 'Euro'],
                ['GL', 'GRL', 'Greenland', 299, 'DKK', 'Danish Krone'],
                ['GD', 'GRD', 'Grenada', 1473, 'XCD', 'East Caribbean Dollar'],
                ['GP', 'GLP', 'Guadeloupe', 590, 'EUR', 'Euro'],
                ['GU', 'GUM', 'Guam', 1671, 'USD', 'US Dollar'],
                ['GT', 'GTM', 'Guatemala', 502, 'GTQ', 'Guatemalan Quetzal'],
                ['GN', 'GIN', 'Guinea', 224, 'GNF', 'Guinean Franc'],
                ['GW', 'GNB', 'Guinea-Bissau', 245, 'XOF', 'CFA Franc BCEAO'],
                ['GY', 'GUY', 'Guyana', 592, 'GYD', 'Guyanaese Dollar'],
                ['HT', 'HTI', 'Haiti', 509, 'HTG', 'Haitian Gourde'],
                ['HM', 'HMD', 'Heard Island and Mcdonald Islands', 672, 'AUD', 'Australian Dollar'],
                ['VA', 'VAT', 'Vatican City State', 39, 'EUR', 'Euro'],
                ['HN', 'HND', 'Honduras', 504, 'HNL', 'Honduran Lempira'],
                ['HK', 'HKG', 'Hong Kong', 852, 'HKD', 'Hong Kong Dollar'],
                ['HU', 'HUN', 'Hungary', 36, 'HUF', 'Hungarian Forint'],
                ['IS', 'ISL', 'Iceland', 354, 'ISK', 'Icelandic Króna'],
                ['IN', 'IND', 'India', 91, 'INR', 'Indian Rupee'],
                ['ID', 'IDN', 'Indonesia', 62, 'IDR', 'Indonesian Rupiah'],
                ['IR', 'IRN', 'Iran, Islamic Republic of', 98, 'IRR', 'Iranian Rial'],
                ['IQ', 'IRQ', 'Iraq', 964, 'IQD', 'Iraqi Dinar'],
                ['IE', 'IRL', 'Ireland', 353, 'EUR', 'Euro'],
                ['IL', 'ISR', 'Israel', 972, 'ILS', 'Israeli New Sheqel'],
                ['IT', 'ITA', 'Italy', 39, 'EUR', 'Euro'],
                ['JM', 'JAM', 'Jamaica', 1876, 'JMD', 'Jamaican Dollar'],
                ['JP', 'JPN', 'Japan', 81, 'JPY', 'Japanese Yen'],
                ['JO', 'JOR', 'Jordan', 962, 'JOD', 'Jordanian Dinar'],
                ['KZ', 'KAZ', 'Kazakhstan', 7, 'KZT', 'Kazakhstani Tenge'],
                ['KE', 'KEN', 'Kenya', 254, 'KES', 'Kenyan Shilling'],
                ['KI', 'KIR', 'Kiribati', 686, 'AUD', 'Australian Dollar'],
                ['KP', 'PRK', 'Korea, Democratic People\'s Republic of', 850, 'KPW', 'North Korean Won'],
                ['KR', 'KOR', 'Korea, Republic of', 82, 'KRW', 'South Korean Won'],
                ['KW', 'KWT', 'Kuwait', 965, 'KWD', 'Kuwaiti Dinar'],
                ['KG', 'KGZ', 'Kyrgyzstan', 996, 'KGS', 'Kyrgystani Som'],
                ['LA', 'LAO', 'Lao People\'s Democratic Republic', 856, 'LAK', 'Laotian Kip'],
                ['LV', 'LVA', 'Latvia', 371, 'EUR', 'Euro'],
                ['LB', 'LBN', 'Lebanon', 961, 'LBP', 'Lebanese Pound'],
                ['LS', 'LSO', 'Lesotho', 266, 'LSL', 'Lesotho Loti'],
                ['LR', 'LBR', 'Liberia', 231, 'LRD', 'Liberian Dollar'],
                ['LY', 'LBY', 'Libyan Arab Jamahiriya', 218, 'LYD', 'Libyan Dinar'],
                ['LI', 'LIE', 'Liechtenstein', 423, 'CHF', 'Swiss Franc'],
                ['LT', 'LTU', 'Lithuania', 370, 'EUR', 'Euro'],
                ['LU', 'LUX', 'Luxembourg', 352, 'EUR', 'Euro'],
                ['MO', 'MAC', 'Macao', 853, 'MOP', 'Macanese Pataca'],
                ['MK', 'MKD', 'Macedonia, the Former Yugoslav Republic of', 389, 'MKD', 'Macedonian Denar'],
                ['MG', 'MDG', 'Madagascar', 261, 'MGA', 'Malagasy Ariary'],
                ['MW', 'MWI', 'Malawi', 265, 'MWK', 'Malawian Kwacha'],
                ['MY', 'MYS', 'Malaysia', 60, 'MYR', 'Malaysian Ringgit'],
                ['MV', 'MDV', 'Maldives', 960, 'MVR', 'Maldivian Rufiyaa'],
                ['ML', 'MLI', 'Mali', 223, 'XOF', 'CFA Franc BCEAO'],
                ['MT', 'MLT', 'Malta', 356, 'EUR', 'Euro'],
                ['MH', 'MHL', 'Marshall Islands', 692, 'USD', 'US Dollar'],
                ['MQ', 'MTQ', 'Martinique', 596, 'EUR', 'Euro'],
                ['MR', 'MRT', 'Mauritania', 222, 'MRO', 'Mauritanian Ouguiya'],
                ['MU', 'MUS', 'Mauritius', 230, 'MUR', 'Mauritian Rupee'],
                ['YT', 'MYT', 'Mayotte', 269, 'EUR', 'Euro'],
                ['MX', 'MEX', 'Mexico', 52, 'MXN', 'Mexican Peso'],
                ['FM', 'FSM', 'Micronesia, Federated States of', 691, 'USD', 'US Dollar'],
                ['MD', 'MDA', 'Moldova, Republic of', 373, 'MDL', 'Moldovan Leu'],
                ['MC', 'MCO', 'Monaco', 377, 'EUR', 'Euro'],
                ['MN', 'MNG', 'Mongolia', 976, 'MNT', 'Mongolian Tugrik'],
                ['MS', 'MSR', 'Montserrat', 1664, 'XCD', 'East Caribbean Dollar'],
                ['MA', 'MAR', 'Morocco', 212, 'MAD', 'Moroccan Dirham'],
                ['MZ', 'MOZ', 'Mozambique', 258, 'MZN', 'Mozambican Metical'],
                ['MM', 'MMR', 'Myanmar', 95, 'MMK', 'Myanmar Kyat'],
                ['NA', 'NAM', 'Namibia', 264, 'NAD', 'Namibian Dollar'],
                ['NR', 'NRU', 'Nauru', 674, 'AUD', 'Australian Dollar'],
                ['NP', 'NPL', 'Nepal', 977, 'NPR', 'Nepalese Rupee'],
                ['NL', 'NLD', 'Netherlands', 31, 'EUR', 'Euro'],
                ['AN', 'ANT', 'Netherlands Antilles', 599, 'ANG', 'Netherlands Antillean guilder'],
                ['NC', 'NCL', 'New Caledonia', 687, 'XPF', 'CFP Franc'],
                ['NZ', 'NZL', 'New Zealand', 64, 'NZD', 'New Zealand Dollar'],
                ['NI', 'NIC', 'Nicaragua', 505, 'NIO', 'Nicaraguan Córdoba'],
                ['NE', 'NER', 'Niger', 227, 'XOF', 'CFA Franc BCEAO'],
                ['NG', 'NGA', 'Nigeria', 234, 'NGN', 'Nigerian Naira'],
                ['NU', 'NIU', 'Niue', 683, 'NZD', 'New Zealand Dollar'],
                ['NF', 'NFK', 'Norfolk Island', 672, 'AUD', 'Australian Dollar'],
                ['MP', 'MNP', 'Northern Mariana Islands', 1670, 'USD', 'US Dollar'],
                ['NO', 'NOR', 'Norway', 47, 'NOK', 'Norwegian Krone'],
                ['OM', 'OMN', 'Oman', 968, 'OMR', 'Omani Rial'],
                ['PK', 'PAK', 'Pakistan', 92, 'PKR', 'Pakistani Rupee'],
                ['PW', 'PLW', 'Palau', 680, 'USD', 'US Dollar'],
                ['PS', 'PSE', 'Palestinian Territory, Occupied', 970, 'JOD', 'Jordanian Dinar'],
                ['PA', 'PAN', 'Panama', 507, 'PAB', 'Panamanian Balboa'],
                ['PG', 'PNG', 'Papua New Guinea', 675, 'PGK', 'Papua New Guinean Kina'],
                ['PY', 'PRY', 'Paraguay', 595, 'PYG', 'Paraguayan Guarani'],
                ['PE', 'PER', 'Peru', 51, 'PEN', 'Peruvian Nuevo Sol'],
                ['PH', 'PHL', 'Philippines', 63, 'PHP', 'Philippine Peso'],
                ['PN', 'PCN', 'Pitcairn', 64, 'NZD', 'New Zealand Dollar'],
                ['PL', 'POL', 'Poland', 48, 'PLN', 'Polish Zloty'],
                ['PT', 'PRT', 'Portugal', 351, 'EUR', 'Euro'],
                ['PR', 'PRI', 'Puerto Rico', 1787, 'USD', 'US Dollar'],
                ['QA', 'QAT', 'Qatar', 974, 'QAR', 'Qatari Rial'],
                ['RE', 'REU', 'Reunion', 262, 'EUR', 'Euro'],
                ['RO', 'ROM', 'Romania', 40, 'RON', 'Leu România'],
                ['RU', 'RUS', 'Russian Federation', 70, 'RUB', 'Russian Ruble'],
                ['RW', 'RWA', 'Rwanda', 250, 'RWF', 'Rwandan Franc'],
                ['SH', 'SHN', 'Saint Helena', 290, 'SHP', 'St. Helena Pound'],
                ['KN', 'KNA', 'Saint Kitts and Nevis', 1869, 'XCD', 'East Caribbean Dollar'],
                ['LC', 'LCA', 'Saint Lucia', 1758, 'XCD', 'East Caribbean Dollar'],
                ['PM', 'SPM', 'Saint Pierre and Miquelon', 508, 'EUR', 'Euro'],
                ['VC', 'VCT', 'Saint Vincent and the Grenadines', 1784, 'XCD', 'East Caribbean Dollar'],
                ['WS', 'WSM', 'Samoa', 684, 'WST', 'Samoan Tala'],
                ['SM', 'SMR', 'San Marino', 378, 'EUR', 'Euro'],
                ['ST', 'STP', 'Sao Tome and Principe', 239, 'STD', 'São Tomé & Príncipe Dobra'],
                ['SA', 'SAU', 'Saudi Arabia', 966, 'SAR', 'Saudi Riyal'],
                ['SN', 'SEN', 'Senegal', 221, 'XOF', 'CFA Franc BCEAO'],
                ['CS', 'SCG', 'Serbia and Montenegro', 381, 'EUR', 'Euro'],
                ['SC', 'SYC', 'Seychelles', 248, 'SCR', 'Seychellois Rupee'],
                ['SL', 'SLE', 'Sierra Leone', 232, 'SLL', 'Sierra Leonean Leone'],
                ['SG', 'SGP', 'Singapore', 65, 'SGD', 'Singapore Dollar'],
                ['SK', 'SVK', 'Slovakia', 421, 'EUR', 'Euro'],
                ['SI', 'SVN', 'Slovenia', 386, 'EUR', 'Euro'],
                ['SB', 'SLB', 'Solomon Islands', 677, 'SBD', 'Solomon Islands Dollar'],
                ['SO', 'SOM', 'Somalia', 252, 'SOS', 'Somali Shilling'],
                ['ZA', 'ZAF', 'South Africa', 27, 'ZAR', 'South African Rand'],
                ['GS', 'SGS', 'South Georgia and the South Sandwich Islands', 500, 'GBP', 'British Pound Sterling'],
                ['ES', 'ESP', 'Spain', 34, 'EUR', 'Euro'],
                ['LK', 'LKA', 'Sri Lanka', 94, 'LKR', 'Sri Lankan Rupee'],
                ['SD', 'SDN', 'Sudan', 249, 'SDG', 'Sudanese Pound'],
                ['SR', 'SUR', 'Suriname', 597, 'SRD', 'Surinamese Dollar'],
                ['SJ', 'SJM', 'Svalbard and Jan Mayen', 47, 'NOK', 'Norwegian Krone'],
                ['SZ', 'SWZ', 'Swaziland', 268, 'SZL', 'Swazi Lilangeni'],
                ['SE', 'SWE', 'Sweden', 46, 'SEK', 'Swedish Krona'],
                ['CH', 'CHE', 'Switzerland', 41, 'CHF', 'Swiss Franc'],
                ['SY', 'SYR', 'Syrian Arab Republic', 963, 'SYP', 'Syrian Pound'],
                ['TW', 'TWN', 'Taiwan, Province of China', 886, 'TWD', 'New Taiwan Dollar'],
                ['TJ', 'TJK', 'Tajikistan', 992, 'TJS', 'Tajikistani Somoni'],
                ['TZ', 'TZA', 'Tanzania, United Republic of', 255, 'TZS', 'Tanzanian Shilling'],
                ['TH', 'THA', 'Thailand', 66, 'THB', 'Thai Baht'],
                ['TL', 'TLS', 'Timor-Leste', 670, 'USD', 'US Dollar'],
                ['TG', 'TGO', 'Togo', 228, 'XOF', 'CFA Franc BCEAO'],
                ['TK', 'TKL', 'Tokelau', 690, 'NZD', 'New Zealand Dollar'],
                ['TO', 'TON', 'Tonga', 676, 'TOP', 'Tongan Paʻanga'],
                ['TT', 'TTO', 'Trinidad and Tobago', 1868, 'TTD', 'Trinidad & Tobago Dollar'],
                ['TN', 'TUN', 'Tunisia', 216, 'TND', 'Tunisian Dinar'],
                ['TR', 'TUR', 'Turkey', 90, 'TRY', 'Turkish Lira'],
                ['TM', 'TKM', 'Turkmenistan', 993, 'TMT', 'Turkmenistani Manat'],
                ['TC', 'TCA', 'Turks and Caicos Islands', 1649, 'USD', 'US Dollar'],
                ['TV', 'TUV', 'Tuvalu', 688, 'AUD', 'Australian Dollar'],
                ['UG', 'UGA', 'Uganda', 256, 'UGX', 'Ugandan Shilling'],
                ['UA', 'UKR', 'Ukraine', 380, 'UAH', 'Ukrainian Hryvnia'],
                ['AE', 'ARE', 'United Arab Emirates', 971, 'AED', 'United Arab Emirates Dirham'],
                ['GB', 'GBR', 'United Kingdom', 44, 'GBP', 'British Pound Sterling'],
                ['US', 'USA', 'United States', 1, 'USD', 'US Dollar'],
                ['UM', 'UMI', 'United States Minor Outlying Islands', 1, 'USD', 'US Dollar'],
                ['UY', 'URY', 'Uruguay', 598, 'UYU', 'Uruguayan Peso'],
                ['UZ', 'UZB', 'Uzbekistan', 998, 'UZS', 'Uzbekistan Som'],
                ['VU', 'VUT', 'Vanuatu', 678, 'VUV', 'Vanuatu Vatu'],
                ['VE', 'VEN', 'Venezuela', 58, 'VEF', 'Venezuelan Bolívar'],
                ['VN', 'VNM', 'Viet Nam', 84, 'VND', 'Vietnamese Dong'],
                ['VG', 'VGB', 'Virgin Islands, British', 1284, 'USD', 'US Dollar'],
                ['VI', 'VIR', 'Virgin Islands, U.s.', 1340, 'USD', 'US Dollar'],
                ['WF', 'WLF', 'Wallis and Futuna', 681, 'XPF', 'CFP Franc'],
                ['EH', 'ESH', 'Western Sahara', 212, 'MAD', 'Moroccan Dirham'],
                ['YE', 'YEM', 'Yemen', 967, 'YER', 'Yemeni Rial'],
                ['ZM', 'ZMB', 'Zambia', 260, 'ZMW', 'Zambian Kwacha'],
                ['ZW', 'ZWE', 'Zimbabwe', 263, 'USD', 'US Dollar'],
            ];

            // Favorite currencies
            $fav_countries = ['USA', 'CHN', 'IND', 'SGP', 'GBR', 'VNM', 'DEU', 'FRA'];

            $now = now();
            $data = array_map(function ($country) use ($fav_countries, $now) {
                return [
                    'alpha2' => $country[0],
                    'alpha3' => $country[1],
                    'country_name' => $country[2],
                    'phone_code' => $country[3],
                    'curr_code' => $country[4],
                    'curr_name' => $country[5],
                    'is_fav' => in_array($country[1], $fav_countries),
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }, $countries);
            \App\Models\Country::insert($data);
            $this->command->info('Countries table seeded!');
        });
    }
}
