<?php

namespace Database\Seeders\InitialData;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Product::withoutEvents(function () {
            $products = [
                ["product_name" => "Lactobacillus Acidophilus", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '5kg/túi'],
                ["product_name" => "Lactobacillus Plantarum", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Streptococcus Faecalis", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Lactobacillus Sporogenes", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Bifidobacterium Lactis", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Saccharomyces Boulardii Microencapsulated", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '10kg/túi'],
                ["product_name" => "Bacillus Subtilis", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Bacillus Clausii", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Lactobacillus Acidophilus", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Saccharomyces Boulardii", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Clostridium Butyricum", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Lactobacillus Reuteri", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Lactobacillus Casei", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Lactobacillus Rhamnosus", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Lacto Bacillus Fermentum 5X10^10 Cfu/G", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Streptococcus Thermophilus", "cat_code" => "BACT", "mfg_code" => "METE", "packing_code" => '1kg/túi'],
                ["product_name" => "Silicagel 2-4Mm", "cat_code" => "CHEM", "mfg_code" => "HONGLIN", "packing_code" => '25kg/bao'],
                ["product_name" => "Silicagel 1-3Mm", "cat_code" => "CHEM", "mfg_code" => "HONGLIN", "packing_code" => '25kg/bao'],
                ["product_name" => "Crotamiton", "cat_code" => "CHEM", "mfg_code" => "HEBEI", "packing_code" => '1kg/túi'],
                ["product_name" => "Polyhexamethylene Biguanidine Hydrochloride Solution", "cat_code" => "CHEM", "mfg_code" => "DASHENG", "packing_code" => '5kg/lon'],
                ["product_name" => "Clotrimazole", "cat_code" => "CHEM", "mfg_code" => "HANPU", "packing_code" => '1kg/túi'],
                ["product_name" => "Gleptofferon 20%", "cat_code" => "CHEM", "mfg_code" => "VICTOR", "packing_code" => '1l/chai'],
                ["product_name" => "Hydroxyaluminum Distearate", "cat_code" => "CHEM", "mfg_code" => "FORTUNA", "packing_code" => '5kg/túi'],
                ["product_name" => "Gleptoferron 20%", "cat_code" => "CHEM", "mfg_code" => "VICTOR", "packing_code" => '100ml/lọ'],
                ["product_name" => "Ceftiofur Sodium", "cat_code" => "CHEM", "mfg_code" => "AMICOGEN", "packing_code" => '25g/chai'],
                ["product_name" => "Ethonas Peg 400", "cat_code" => "CHEM", "mfg_code" => "PATRONAS", "packing_code" => '230kg/phuy'],
                ["product_name" => "Cồn Công Nghiệp 96%", "cat_code" => "CHEM", "mfg_code" => "HIENNHUNG", "packing_code" => '210l/phuy'],
                ["product_name" => "Fipronil", "cat_code" => "CHEM", "mfg_code" => "LUXI", "packing_code" => '1kg/túi'],
                ["product_name" => "Beta Cyclodextrin", "cat_code" => "CHEM", "mfg_code" => "QIANHUI", "packing_code" => '200g/túi'],
                ["product_name" => "Itraconazole (Micronized)", "cat_code" => "CHEM", "mfg_code" => "SMILAX", "packing_code" => '100g/túi'],
                ["product_name" => "Gleptoferron 20%", "cat_code" => "CHEM", "mfg_code" => "VICTOR", "packing_code" => '30kg/thùng'],
                ["product_name" => "Iron Dextran 10%", "cat_code" => "CHEM", "mfg_code" => "NONGDA", "packing_code" => '100ml/lọ'],
                ["product_name" => "Iron Dextran 20%", "cat_code" => "CHEM", "mfg_code" => "NONGDA", "packing_code" => '100ml/lọ'],
                ["product_name" => "S-Adenosyl-L-Methionine Disulfate Tosylate", "cat_code" => "CHEM", "mfg_code" => "JINCHENG", "packing_code" => '1kg/túi'],
                ["product_name" => "L-Glutathione", "cat_code" => "CHEM", "mfg_code" => "JINCHENG", "packing_code" => '1kg/túi'],
                ["product_name" => "Sanguinol", "cat_code" => "CHEM", "mfg_code" => "RONGDA", "packing_code" => '50g/túi'],
                ["product_name" => "L-Ornithine L-Aspartate", "cat_code" => "CHEM", "mfg_code" => "HOYO", "packing_code" => '1kg/túi'],
                ["product_name" => "Procaine Hydrochloride", "cat_code" => "CHEM", "mfg_code" => "BAIKANG", "packing_code" => '100g/túi'],
                ["product_name" => "Procaine Hydrochloride", "cat_code" => "CHEM", "mfg_code" => "WUSHENG", "packing_code" => '100g/túi'],
                ["product_name" => "Itraconazole (Micronized)", "cat_code" => "CHEM", "mfg_code" => "SMILAX", "packing_code" => '1kg/thùng'],
                ["product_name" => "Hydroxyaluminum Distearate", "cat_code" => "CHEM", "mfg_code" => "FORTUNA", "packing_code" => '10kg/thùng'],
                ["product_name" => "Racecadotril Ep10", "cat_code" => "CHEM", "mfg_code" => "BOYUAN", "packing_code" => '1kg/thùng'],
                ["product_name" => "Idacol Brown Ht V850:1-40", "cat_code" => "CHEM", "mfg_code" => "DYECHEM", "packing_code" => '25kg/thùng'],
                ["product_name" => "Gleptoferron 20%", "cat_code" => "CHEM", "mfg_code" => "VICTOR", "packing_code" => '5l/can'],
                ["product_name" => "Tricaine Methaesulfonate", "cat_code" => "CHEM", "mfg_code" => "FORTUNA", "packing_code" => '50g/túi'],
                ["product_name" => "Azithromycin", "cat_code" => "DRUG", "mfg_code" => "ZJGUOBANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Piracetam", "cat_code" => "DRUG", "mfg_code" => "YUEHUA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Mannitol", "cat_code" => "DRUG", "mfg_code" => "HUAXU", "packing_code" => '25kg/thùng'],
                ["product_name" => "Ibrutinib", "cat_code" => "DRUG", "mfg_code" => "NATCO", "packing_code" => '12.5kg/thùng'],
                ["product_name" => "Nilotinib Hydrochloride Monohydrate", "cat_code" => "DRUG", "mfg_code" => "SDLIXIN", "packing_code" => '8kg/thùng'],
                ["product_name" => "Bicalutamide", "cat_code" => "DRUG", "mfg_code" => "ARCADIA", "packing_code" => '6kg/thùng'],
                ["product_name" => "Linagliptin", "cat_code" => "DRUG", "mfg_code" => "BIOCON", "packing_code" => '2.7kg/thùng'],
                ["product_name" => "Palbociclib", "cat_code" => "DRUG", "mfg_code" => "SIONC", "packing_code" => '5.5kg/thùng'],
                ["product_name" => "Agomelatine (Micronized)", "cat_code" => "DRUG", "mfg_code" => "MEHTA", "packing_code" => '24kg/thùng'],
                ["product_name" => "Colchicine", "cat_code" => "DRUG", "mfg_code" => "SARV", "packing_code" => '500g/túi'],
                ["product_name" => "Linagliptin", "cat_code" => "DRUG", "mfg_code" => "HONOURLAB", "packing_code" => '300g/túi'],
                ["product_name" => "Linagliptin", "cat_code" => "DRUG", "mfg_code" => "HONOURLAB", "packing_code" => '4kg/thùng'],
                ["product_name" => "Lenvatinib", "cat_code" => "DRUG", "mfg_code" => "XIDI", "packing_code" => '1350g/thùng'],
                ["product_name" => "Cefradine", "cat_code" => "DRUG", "mfg_code" => "NCPC", "packing_code" => '25kg/thùng'],
                ["product_name" => "Clotrimazole", "cat_code" => "DRUG", "mfg_code" => "HANPU", "packing_code" => '25kg/thùng'],
                ["product_name" => "Sulpiride", "cat_code" => "DRUG", "mfg_code" => "DIYI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Progesterone Micronized", "cat_code" => "DRUG", "mfg_code" => "UNITED-PHARMA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Sulpiride (Micronized)", "cat_code" => "DRUG", "mfg_code" => "DIYI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Candesartan Cilexetil", "cat_code" => "DRUG", "mfg_code" => "RUNDU", "packing_code" => '25kg/thùng'],
                ["product_name" => "Potassium Guaiacolsulfonate", "cat_code" => "DRUG", "mfg_code" => "HAIZHOU", "packing_code" => '1kg/túi'],
                ["product_name" => "Papain 50000Iu/Mg", "cat_code" => "ENZE", "mfg_code" => "METE", "packing_code" => '5kg/túi'],
                ["product_name" => "Bromelain 2400Gdu/G", "cat_code" => "ENZE", "mfg_code" => "METE", "packing_code" => '25kg/thùng'],
                ["product_name" => "Amylase 10000 Iu/G", "cat_code" => "ENZE", "mfg_code" => "METE", "packing_code" => '5kg/túi'],
                ["product_name" => "Lactase 2000 Iu/G", "cat_code" => "ENZE", "mfg_code" => "METE", "packing_code" => '5kg/túi'],
                ["product_name" => "Lipase 2000 Iu/G", "cat_code" => "ENZE", "mfg_code" => "METE", "packing_code" => '5kg/túi'],
                ["product_name" => "Cellulase 2000 Iu/G", "cat_code" => "ENZE", "mfg_code" => "METE", "packing_code" => '5kg/túi'],
                ["product_name" => "Protease 2000 Iu/G", "cat_code" => "ENZE", "mfg_code" => "METE", "packing_code" => '5kg/túi'],
                ["product_name" => "Maltase 2000 Iu/G", "cat_code" => "ENZE", "mfg_code" => "METE", "packing_code" => '5kg/túi'],
                ["product_name" => "L-Lysine Sulfate", "cat_code" => "FEED", "mfg_code" => "FUFENG", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Threonine", "cat_code" => "FEED", "mfg_code" => "EPPEN", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Lysine Hcl", "cat_code" => "FEED", "mfg_code" => "GOLDENCORN", "packing_code" => '25kg/bao'],
                ["product_name" => "Leader Red 10%", "cat_code" => "FEED", "mfg_code" => "FOSHAN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Leader Yellow 2%", "cat_code" => "FEED", "mfg_code" => "FOSHAN", "packing_code" => '25kg/bao'],
                ["product_name" => "Sodium Bicarbonate", "cat_code" => "FEED", "mfg_code" => "AUIE", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Threonine", "cat_code" => "FEED", "mfg_code" => "FUFENG", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Lysine Hcl", "cat_code" => "FEED", "mfg_code" => "MEIHUA", "packing_code" => '25kg/bao'],
                ["product_name" => "Choline Chloride 60%", "cat_code" => "FEED", "mfg_code" => "JUJIA", "packing_code" => '25kg/bao'],
                ["product_name" => "Choline Chloride 60%", "cat_code" => "FEED", "mfg_code" => "BELONG", "packing_code" => '25kg/bao'],
                ["product_name" => "Ferrous Sulphate Powder", "cat_code" => "FEED", "mfg_code" => "CHEMLAND", "packing_code" => '25kg/bao'],
                ["product_name" => "Ding Su 30: Nguyên Liệu Bổ Sung Sodium Butyrate Trong Tacn", "cat_code" => "FEED", "mfg_code" => "SINGAO", "packing_code" => '25kg/bao'],
                ["product_name" => "Ferrous Sulphate Granular", "cat_code" => "FEED", "mfg_code" => "CHEMLAND", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Lysine Sulfate", "cat_code" => "FEED", "mfg_code" => "CHENGFU", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Threonine", "cat_code" => "FEED", "mfg_code" => "CHENGFU", "packing_code" => '25kg/bao'],
                ["product_name" => "Dl-Methionine", "cat_code" => "FEED", "mfg_code" => "UNISPLENDOUR", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Valine", "cat_code" => "FEED", "mfg_code" => "EPPEN", "packing_code" => '25kg/bao'],
                ["product_name" => "Mnso4", "cat_code" => "FEED", "mfg_code" => "CHEMLAND", "packing_code" => '25kg/bao'],
                ["product_name" => "Znso4", "cat_code" => "FEED", "mfg_code" => "CHEMLAND", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Lysine Sulfate 70%", "cat_code" => "FEED", "mfg_code" => "MEIHUA", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Lysine Sulfate 70%", "cat_code" => "FEED", "mfg_code" => "DONGXIAO", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Threonine", "cat_code" => "FEED", "mfg_code" => "MEIHUA", "packing_code" => '25kg/bao'],
                ["product_name" => "Dextrose Monohydrate", "cat_code" => "FEED", "mfg_code" => "FUFENG", "packing_code" => '25kg/bao'],
                ["product_name" => "Lacto Plus 18-18", "cat_code" => "FEED", "mfg_code" => "LACTO", "packing_code" => '10kg/túi'],
                ["product_name" => "L-Lysine Sulfate 70%", "cat_code" => "FEED", "mfg_code" => "EPPEN", "packing_code" => '25kg/bao'],
                ["product_name" => "Methionine", "cat_code" => "FEED", "mfg_code" => "CJ", "packing_code" => '25kg/bao'],
                ["product_name" => "Copper Sulphate Pentahydrate", "cat_code" => "FEED", "mfg_code" => "CHEMLAND", "packing_code" => '25kg/bao'],
                ["product_name" => "Magnesium Sulfate", "cat_code" => "FEED", "mfg_code" => "CHEMLAND", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Lysine Hcl", "cat_code" => "FEED", "mfg_code" => "EPPEN", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Lysine Hcl", "cat_code" => "FEED", "mfg_code" => "FUFENG", "packing_code" => '25kg/bao'],
                ["product_name" => "L-Lysine Hcl Aj", "cat_code" => "FEED", "mfg_code" => "XINJIANG", "packing_code" => '25kg/bao'],
                ["product_name" => "Lacto Plus 18-18", "cat_code" => "FEED", "mfg_code" => "LACTO", "packing_code" => '20kg/bao'],
                ["product_name" => "Sodium Bicarbonate", "cat_code" => "FEED", "mfg_code" => "JINGHAO", "packing_code" => '25kg/bao'],
                ["product_name" => "Dl-Methionine 99% Percent Feed Grade", "cat_code" => "FEED", "mfg_code" => "SUMITOMO", "packing_code" => '25kg/bao'],
                ["product_name" => "Dicalcium Phosphate", "cat_code" => "FEED", "mfg_code" => "SUNWARD", "packing_code" => '50kg/bao'],
                ["product_name" => "Luctarom Fruity (Hương Cam)", "cat_code" => "FEED", "mfg_code" => "LUCTA", "packing_code" => '25kg/bao'],
                ["product_name" => "Sodium Bicarbonate", "cat_code" => "FEED", "mfg_code" => "ZHONGYUAN", "packing_code" => '25kg/bao'],
                ["product_name" => "Monocalcium Phosphate（Mcp）Feed Grade Granular", "cat_code" => "FEED", "mfg_code" => "YUNNAN", "packing_code" => '25kg/bao'],
                ["product_name" => "Monocalcium Phosphate Feed Grade", "cat_code" => "FEED", "mfg_code" => "TIANBAO", "packing_code" => '50kg/bao'],
                ["product_name" => "Ascorbic Acid (Vitamin C)", "cat_code" => "FEED", "mfg_code" => "LUWEI", "packing_code" => '25kg/thùng'],
                ["product_name" => "L-Lysine Monohydrochloride 98.5% Feed Grade", "cat_code" => "FEED", "mfg_code" => "AJINOMOTO-CN", "packing_code" => '25kg/bao'],
                ["product_name" => "Calcium Formate", "cat_code" => "FEED", "mfg_code" => "KIRNS", "packing_code" => '25kg/bao'],
                ["product_name" => "Lake Of Quinoline Yellow 22-27%", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Black Pn", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Patent Blue V", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Tartrazine 22-27%", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Sunset Yellow 22-27%", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Brilliant Blue 22-27%", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Indigo Carmine 22-27%", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Carmoisine 22-27%", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Oil Soluble Ponceau G", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Koel Neem Green", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Apple Green", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Ponceau 4R", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Tartrazine", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Sunset Yellow", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Allura Red", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Allura Red", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Amaranth", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Amaranth (Acid Red)", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/bao'],
                ["product_name" => "Amaranth", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Apple Green", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Black Pn", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Brilliant Blue", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Brilliant Blue", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Brilliant Blue", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Carmoisine", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Carmoisine", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Carmosine (Acid Red)", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Chocolate Brown Ht", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Chocolate Brown Ht", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Erythrosine", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Erythrosine (Acid Red)", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Erythrosine", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Green S", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Green S", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '20kg/thùng'],
                ["product_name" => "Iron Oxide Black", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Iron Oxide Black", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Iron Oxide Brown", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Iron Oxide Brown", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Iron Oxide Red", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Iron Oxide Red", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Iron Oxide Yellow", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Iron Oxide Yellow", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Koelron", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Allura Red", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Amaranth", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Amaranth", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Brilliant Blue – 22-27%", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Erythrosine - 12-17 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Erythrosine - 12-17 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Erythrosine - 22-27 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Erythrosine - 22-27 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Erythrosine - 32-40 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Erythrosine - 32-40 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Indigo Carmine", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Ponceau 4R - 12-17 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Ponceau 4R - 22-27 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Ponceau 4R - 32-40 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Quinoline Yellow Ws", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Quinoline Yellow Ws", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Quinoline Yellow Ws - 22-27 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Quinoline Yellow Ws - 32-40 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Sunset Yellow - 12-17 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Sunset Yellow - 12-17 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Sunset Yellow - 22-27 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Sunset Yellow - 32-40 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Sunset Yellow - 32-40 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Tartrazine - 12-17 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Tartrazine - 12-17 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Tartrazine - 22-27 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Tartrazine – 32 - 40 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Lake Of Tartrazine – 32 - 40 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Patent Blue V", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Patent Blue V", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Tartrazine – 32 - 40 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Tartrazine – 32 - 40 %", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Sodium Saccharin Anhydrous", "cat_code" => "FOOD", "mfg_code" => "KAIFENG", "packing_code" => '25kg/bao'],
                ["product_name" => "Ascorbic Acid (Vitamin C)", "cat_code" => "FOOD", "mfg_code" => "LUWEI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Quinoline Yellow Ws", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Quinoline Yellow Ws", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Quinoline Yellow Ws (Acid Yellow)", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Quinoline Yellow Ws", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Sunset Yellow", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Sunset Yellow", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Sunset Yellow", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Tartrazine", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Tartrazine (Acid Yellow)", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Titanium Dioxide", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Andrographis Paniculata Dry Extract (Chiết Xuất Xuyên Tâm Liên 5%)", "cat_code" => "FOOD", "mfg_code" => "PANACEA", "packing_code" => '5kg/túi'],
                ["product_name" => "Andrographis Paniculata Dry Extract (Chiết Xuất Xuyên Tâm Liên 10%)", "cat_code" => "FOOD", "mfg_code" => "PANACEA", "packing_code" => '5kg/túi'],
                ["product_name" => "Green Coffee Been Extract ( Chiết Xuất Hạt Cafe Xanh)", "cat_code" => "FOOD", "mfg_code" => "ACETAR", "packing_code" => '25kg/thùng'],
                ["product_name" => "Noni Extract (Chiết Xuất Trái Nhàu)", "cat_code" => "FOOD", "mfg_code" => "SHAANXI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Terminalia Chebula Fruit Extract (Chiết Xuất Quả Chiêu Liêu)", "cat_code" => "FOOD", "mfg_code" => "SHAANXI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Cinnamon Extract (Chiết Xuất Quế)", "cat_code" => "FOOD", "mfg_code" => "SHAANXI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Bamboo Extract (Chiết Xuất Tre)", "cat_code" => "FOOD", "mfg_code" => "SHAANXI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Aloe Vera Extract (Chiết Xuất Lô Hội)", "cat_code" => "FOOD", "mfg_code" => "SHAANXI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Tribulus Terrestris Extract (Chiết Xuất Bạch Tật Lê)", "cat_code" => "FOOD", "mfg_code" => "PANACEA", "packing_code" => '5kg/túi'],
                ["product_name" => "Fenugreek Extrac (Chiết Xuất Cỏ Cà Ri)", "cat_code" => "FOOD", "mfg_code" => "PANACEA", "packing_code" => '5kg/túi'],
                ["product_name" => "Moringa Extract (Chiết Xuất Chùm Ngây)", "cat_code" => "FOOD", "mfg_code" => "PANACEA", "packing_code" => '5kg/túi'],
                ["product_name" => "Licorice Extract (Chiết Xuất Cam Thảo)", "cat_code" => "FOOD", "mfg_code" => "PANACEA", "packing_code" => '5kg/túi'],
                ["product_name" => "Gymnema Extract (Chiết Xuất Dây Thìa Canh)", "cat_code" => "FOOD", "mfg_code" => "PANACEA", "packing_code" => '5kg/túi'],
                ["product_name" => "Boswellia Serrata Extract (Chiết Xuất Nhũ Hương)", "cat_code" => "FOOD", "mfg_code" => "PANACEA", "packing_code" => '5kg/túi'],
                ["product_name" => "Ashwagandha Extract (Chiết Xuất Nhân Sâm Ấn Độ)", "cat_code" => "FOOD", "mfg_code" => "PANACEA", "packing_code" => '5kg/túi'],
                ["product_name" => "Green Tea Extract (Chiết Xuất Trà Xanh)", "cat_code" => "FOOD", "mfg_code" => "PANACEA", "packing_code" => '5kg/túi'],
                ["product_name" => "Tinospora Cordifolia Extract (Chiết Xuất Dây Thần Thông)", "cat_code" => "FOOD", "mfg_code" => "PANACEA", "packing_code" => '3kg/túi'],
                ["product_name" => "Foeniculum Vulgare Extract (Tiểu Hồi Hương)", "cat_code" => "FOOD", "mfg_code" => "SHAANXI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Psoralea Corylifolia Extract (Phá Cố Chỉ)", "cat_code" => "FOOD", "mfg_code" => "SHAANXI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Andrographis Extract (Chiết Xuất Xuyên Tâm Liên)", "cat_code" => "FOOD", "mfg_code" => "SHAANXI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Black Turmeric Extract (Chiết Xuất Nga Truật/ Nghệ Đen)", "cat_code" => "FOOD", "mfg_code" => "SHAANXI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Artemisia Annua Extract (Chiết Xuất Thanh Hao Hoa Vàng)", "cat_code" => "FOOD", "mfg_code" => "SHAANXI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Bacopa Extract (Chiết Xuất Ra Đắng Biển)", "cat_code" => "FOOD", "mfg_code" => "HERBAL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Mucuna Pruriens Extract (Chiết Xuất Đậu Mèo Rừng)", "cat_code" => "FOOD", "mfg_code" => "HERBAL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Asparagus Racemosa Extract (Chiết Xuất Thiên Môn Chùm)", "cat_code" => "FOOD", "mfg_code" => "HERBAL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Ocimum Sanctum Extract (Chiết Xuất Hương Nhu Tía)", "cat_code" => "FOOD", "mfg_code" => "HERBAL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Ponceau G", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Lake Of Carmoisine 22-27%", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '5kg/túi'],
                ["product_name" => "Pea Green", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Ponceau 4R", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Carmoisine", "cat_code" => "FOOD", "mfg_code" => "KOEL", "packing_code" => '1kg/túi'],
                ["product_name" => "Hesperidin", "cat_code" => "FOOD", "mfg_code" => "BENEPURE", "packing_code" => '25kg/thùng'],
                ["product_name" => "Diosmin Micronized", "cat_code" => "FOOD", "mfg_code" => "BENEPURE", "packing_code" => '25kg/thùng'],
                ["product_name" => "Propylene Glycol Usp Grade (Pg)", "cat_code" => "FOOD", "mfg_code" => "DONGYING", "packing_code" => '215kg/phuy'],
                ["product_name" => "D-Fructose-1,6-Diphosphate Sodium", "cat_code" => "FOOD", "mfg_code" => "JIANGSUSEED", "packing_code" => '25kg/thùng'],
                ["product_name" => "Labcot Lactic Acid Bacteria -Gf5", "cat_code" => "FOOD", "mfg_code" => "GENEFERM", "packing_code" => '5kg/thùng'],
                ["product_name" => "Sodium Cyclamate", "cat_code" => "FOOD", "mfg_code" => "NUTA", "packing_code" => '25kg/bao'],
                ["product_name" => "Ascorbic Acid", "cat_code" => "FOOD", "mfg_code" => "CSPC", "packing_code" => '25kg/thùng'],
                ["product_name" => "L-Lysine Hydrochloride (L-Lysine Monohydrochloride)", "cat_code" => "FOOD", "mfg_code" => "HUAYANG", "packing_code" => '25kg/bao'],
                ["product_name" => "Amoxicillin Trihydrate Powder", "cat_code" => "VETT", "mfg_code" => "WEIQIDA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Amoxicillin Trihydrate", "cat_code" => "VETT", "mfg_code" => "UNITED", "packing_code" => '25kg/thùng'],
                ["product_name" => "Amoxicillin Trihydrate Powder", "cat_code" => "VETT", "mfg_code" => "NCPC", "packing_code" => '25kg/thùng'],
                ["product_name" => "Oxytetracycline Hcl (Otc)", "cat_code" => "VETT", "mfg_code" => "DAFENG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Florfenicol", "cat_code" => "VETT", "mfg_code" => "SDGUOBANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Sulfamonomethoxine Sodium", "cat_code" => "VETT", "mfg_code" => "JIANGSU", "packing_code" => '25kg/thùng'],
                ["product_name" => "Cefalexin Powder", "cat_code" => "VETT", "mfg_code" => "NCPC", "packing_code" => '20kg/thùng'],
                ["product_name" => "Sulfamonomethoxine Sodium", "cat_code" => "VETT", "mfg_code" => "TIANHUA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Ampicillin Trihydrate Powder", "cat_code" => "VETT", "mfg_code" => "NCPC", "packing_code" => '25kg/thùng'],
                ["product_name" => "Iron Dextran Solution 10%", "cat_code" => "VETT", "mfg_code" => "GUANGHONG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Ampicillin Trihydrate", "cat_code" => "VETT", "mfg_code" => "WEIQIDA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Albendazole", "cat_code" => "VETT", "mfg_code" => "DAMO", "packing_code" => '25kg/thùng'],
                ["product_name" => "Cefotaxime Sodium", "cat_code" => "VETT", "mfg_code" => "KANGDA", "packing_code" => '10kg/thùng'],
                ["product_name" => "Sulfaquinoxalin Sodium", "cat_code" => "VETT", "mfg_code" => "BEISHA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Thiamphenicol", "cat_code" => "VETT", "mfg_code" => "HANSYN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Enrofloxacin Base", "cat_code" => "VETT", "mfg_code" => "ZJGUOBANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Enrofloxacin Hcl", "cat_code" => "VETT", "mfg_code" => "ZJGUOBANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Sulfadiazine Sodium", "cat_code" => "VETT", "mfg_code" => "WUGAN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Sulfachloropyridazine Sodium", "cat_code" => "VETT", "mfg_code" => "WUGAN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Tylosin Tartrate Powder", "cat_code" => "VETT", "mfg_code" => "TAIYICIN", "packing_code" => '15kg/thùng'],
                ["product_name" => "Norfloxacin Hcl", "cat_code" => "VETT", "mfg_code" => "KANGWEI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Tylosin Tartrate", "cat_code" => "VETT", "mfg_code" => "LUKANG-SHELILE", "packing_code" => '25kg/thùng'],
                ["product_name" => "Norfloxacin Hcl", "cat_code" => "VETT", "mfg_code" => "ZHENGMU", "packing_code" => '25kg/thùng'],
                ["product_name" => "Phenylbutazone", "cat_code" => "VETT", "mfg_code" => "JINGHUA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Potassium Clavulanate With Avicel (1 :1)", "cat_code" => "VETT", "mfg_code" => "WEIQIDA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Florfenicol", "cat_code" => "VETT", "mfg_code" => "KANGMU", "packing_code" => '25kg/thùng'],
                ["product_name" => "Diclazuril", "cat_code" => "VETT", "mfg_code" => "ZJGUOBANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Trimethoprim Bp (Micronized) Tmp", "cat_code" => "VETT", "mfg_code" => "ANDHRA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Sulfamethoxazole (Smz)", "cat_code" => "VETT", "mfg_code" => "VIRCHOW", "packing_code" => '25kg/thùng'],
                ["product_name" => "Piracetam", "cat_code" => "VETT", "mfg_code" => "NE", "packing_code" => '25kg/thùng'],
                ["product_name" => "Vitamin K1", "cat_code" => "VETT", "mfg_code" => "ANHUI", "packing_code" => '1kg/túi'],
                ["product_name" => "Oxytocin", "cat_code" => "VETT", "mfg_code" => "XINYING", "packing_code" => '1g/túi'],
                ["product_name" => "Paracetamol", "cat_code" => "VETT", "mfg_code" => "BAIKANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Doxycycline Hyclate", "cat_code" => "VETT", "mfg_code" => "JIUPENG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Berberine Hydrochloride", "cat_code" => "VETT", "mfg_code" => "YUXIN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Toltrazuril", "cat_code" => "VETT", "mfg_code" => "MASTEAM", "packing_code" => '5kg/túi'],
                ["product_name" => "Ketoconazole", "cat_code" => "VETT", "mfg_code" => "AARTI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Amoxicillin Trihydrate Bp Micronized", "cat_code" => "VETT", "mfg_code" => "AUROBINDO", "packing_code" => '25kg/thùng'],
                ["product_name" => "Azithromycin", "cat_code" => "VETT", "mfg_code" => "ZJGUOBANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Marbofloxacin", "cat_code" => "VETT", "mfg_code" => "ZJGUOBANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Diclofenac Sodium", "cat_code" => "VETT", "mfg_code" => "AARTI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Sulfachloropyrazine Sodium", "cat_code" => "VETT", "mfg_code" => "WUGAN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Lincomycin Hcl", "cat_code" => "VETT", "mfg_code" => "TOPFOND", "packing_code" => '20bou/thùng'],
                ["product_name" => "Glutaraldehyde 50%", "cat_code" => "VETT", "mfg_code" => "SHENGLING", "packing_code" => '220kg/phuy'],
                ["product_name" => "Mebendazole", "cat_code" => "VETT", "mfg_code" => "KAMALLE", "packing_code" => '25kg/thùng'],
                ["product_name" => "Miconazole Nitrate", "cat_code" => "VETT", "mfg_code" => "HANPU", "packing_code" => '25kg/thùng'],
                ["product_name" => "Spectinomycin Hcl", "cat_code" => "VETT", "mfg_code" => "JINHUA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Metamizole Sodium (Analgin C)", "cat_code" => "VETT", "mfg_code" => "JIHENG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Tiamulin Hydrogen Fumarate", "cat_code" => "VETT", "mfg_code" => "VEYONG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Sulfaguanidine", "cat_code" => "VETT", "mfg_code" => "WUGAN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Sulfadimidine Sodium", "cat_code" => "VETT", "mfg_code" => "WUGAN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Ceftiofur Hcl", "cat_code" => "VETT", "mfg_code" => "JIULONG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Trimethoprim", "cat_code" => "VETT", "mfg_code" => "FUKANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Sulfadimethoxine Sodium", "cat_code" => "VETT", "mfg_code" => "SHUNDA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Paracetamol", "cat_code" => "VETT", "mfg_code" => "BBCA", "packing_code" => '25kg/bao'],
                ["product_name" => "Ivermectin", "cat_code" => "VETT", "mfg_code" => "VEYONG", "packing_code" => '1kg/túi'],
                ["product_name" => "Sulfachloropyrazine Sodium Monohydrate", "cat_code" => "VETT", "mfg_code" => "TIANHE", "packing_code" => '25kg/thùng'],
                ["product_name" => "Paracetamol", "cat_code" => "VETT", "mfg_code" => "BAIKANG", "packing_code" => '25kg/bao'],
                ["product_name" => "Tiamulin Fumarate", "cat_code" => "VETT", "mfg_code" => "QILU", "packing_code" => '25kg/thùng'],
                ["product_name" => "Tilmicosin Phosphate", "cat_code" => "VETT", "mfg_code" => "JIULONG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Ceftriaxone Sodium Ep", "cat_code" => "VETT", "mfg_code" => "LUKANG", "packing_code" => '5kg/túi'],
                ["product_name" => "Fosfomycin Calcium", "cat_code" => "VETT", "mfg_code" => "NE", "packing_code" => '20kg/thùng'],
                ["product_name" => "Antipyrine", "cat_code" => "VETT", "mfg_code" => "HAISEN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Propylene Glycol Usp Grade (Pg)", "cat_code" => "VETT", "mfg_code" => "DONGYING", "packing_code" => '215kg/phuy'],
                ["product_name" => "N-Methyl Pyrrolidone (Nmp)", "cat_code" => "VETT", "mfg_code" => "NEM-MAT", "packing_code" => '200kg/phuy'],
                ["product_name" => "Gentamicin Sulfate", "cat_code" => "VETT", "mfg_code" => "RENHUA", "packing_code" => '10bou/thùng'],
                ["product_name" => "Niclosamide Anhydrous Bp2024", "cat_code" => "VETT", "mfg_code" => "ADANI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Marbofloxacin", "cat_code" => "VETT", "mfg_code" => "ZJGUOBANG", "packing_code" => '2kg/thùng'],
                ["product_name" => "Colistin Sulfate", "cat_code" => "VETT", "mfg_code" => "DACHENG", "packing_code" => '20kg/thùng'],
                ["product_name" => "Dodecyl Dimethyl Benzyl Ammonium Chloride 80%", "cat_code" => "VETT", "mfg_code" => "TAIHE", "packing_code" => '200kg/phuy'],
                ["product_name" => "Tylosin Base", "cat_code" => "VETT", "mfg_code" => "LUKANG-SHELILE", "packing_code" => '20kg/thùng'],
                ["product_name" => "Trimethoprim Usp (Micronized)", "cat_code" => "VETT", "mfg_code" => "ANDHRA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Cefotaxime Sodium (Sterile)", "cat_code" => "VETT", "mfg_code" => "SDSALUBRIS", "packing_code" => '10kg/thùng'],
                ["product_name" => "Cefotaxime Sodium", "cat_code" => "VETT", "mfg_code" => "SDSALUBRIS", "packing_code" => '10kg/thùng'],
                ["product_name" => "Sulfadimidine Sodium", "cat_code" => "VETT", "mfg_code" => "ZHENGMU", "packing_code" => '25kg/thùng'],
                ["product_name" => "Neomycin Sulfate (Usp)", "cat_code" => "VETT", "mfg_code" => "SANXIA", "packing_code" => '20bou/thùng'],
                ["product_name" => "S-Methoprene", "cat_code" => "VETT", "mfg_code" => "SEQUENT", "packing_code" => '2kg/thùng'],
                ["product_name" => "Erythromycin Thiocyanate", "cat_code" => "VETT", "mfg_code" => "HEC", "packing_code" => '20kg/thùng'],
                ["product_name" => "Amoxicillin Trihydrate Bp Micronized", "cat_code" => "VETT", "mfg_code" => "APITO", "packing_code" => '25kg/thùng'],
                ["product_name" => "Paracetamol", "cat_code" => "VETT", "mfg_code" => "BBCA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Doxycycline Hyclate", "cat_code" => "VETT", "mfg_code" => "KUNSHAN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Fosfomycin Calcium Ep", "cat_code" => "VETT", "mfg_code" => "NE", "packing_code" => '20kg/thùng'],
                ["product_name" => "Sulfadimethoxine Sodium", "cat_code" => "VETT", "mfg_code" => "APELOA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Benzylpenicillin Procaine Sterile", "cat_code" => "VETT", "mfg_code" => "NCPC", "packing_code" => '20bou/thùng'],
                ["product_name" => "Thiamphenicol", "cat_code" => "VETT", "mfg_code" => "LIBERTY", "packing_code" => '25kg/thùng'],
                ["product_name" => "Trypsin 2500Iu", "cat_code" => "VETT", "mfg_code" => "GEYUAN", "packing_code" => '1kg/thùng'],
                ["product_name" => "Trypsin", "cat_code" => "VETT", "mfg_code" => "GEYUAN", "packing_code" => '1kg/túi'],
                ["product_name" => "Dexamethasone Sodium Phosphate", "cat_code" => "VETT", "mfg_code" => "TIANYAO", "packing_code" => '1kg/túi'],
                ["product_name" => "Cefixime Usp44", "cat_code" => "VETT", "mfg_code" => "COVALENT", "packing_code" => '25kg/thùng'],
                ["product_name" => "Dexamethasone Sodium Phosphate Usp36", "cat_code" => "VETT", "mfg_code" => "RUIJIN", "packing_code" => '1kg/thùng'],
                ["product_name" => "Fosfomycin Sodium Ep", "cat_code" => "VETT", "mfg_code" => "NE", "packing_code" => '20kg/thùng'],
                ["product_name" => "Bromhexine Hydrochloride (Bp/Ep)", "cat_code" => "VETT", "mfg_code" => "OREX", "packing_code" => '25kg/thùng'],
                ["product_name" => "Gentamicin Sulfate Bp2002/Ep4", "cat_code" => "VETT", "mfg_code" => "FUAN", "packing_code" => '10bou/thùng'],
                ["product_name" => "Dexamethasone Acetate (Ep/Usp)", "cat_code" => "VETT", "mfg_code" => "TIANYAO", "packing_code" => '1kg/túi'],
                ["product_name" => "Gleptoferron 20%", "cat_code" => "VETT", "mfg_code" => "VICTOR", "packing_code" => '30kg/thùng'],
                ["product_name" => "Fipronil", "cat_code" => "VETT", "mfg_code" => "LUXI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Iron Dextran 10%", "cat_code" => "VETT", "mfg_code" => "VICTOR", "packing_code" => '25kg/thùng'],
                ["product_name" => "Colistin Sulfate", "cat_code" => "VETT", "mfg_code" => "APELOA", "packing_code" => '20kg/thùng'],
                ["product_name" => "Bacitracin Methylene Disalicylate Soluble Powder (50%)", "cat_code" => "VETT", "mfg_code" => "LIFECOME", "packing_code" => '25kg/thùng'],
                ["product_name" => "Acetylsalicylic Acid", "cat_code" => "VETT", "mfg_code" => "XINHUA", "packing_code" => '25kg/thùng'],
                ["product_name" => "Alpha Chymotrypsin", "cat_code" => "VETT", "mfg_code" => "GEYUAN", "packing_code" => '5kg/túi'],
                ["product_name" => "Norfloxacin", "cat_code" => "VETT", "mfg_code" => "KANGWEI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Thiamphenicol", "cat_code" => "VETT", "mfg_code" => "RUNKANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Difloxacin Hydrochloride", "cat_code" => "VETT", "mfg_code" => "TAIMAI", "packing_code" => '25kg/thùng'],
                ["product_name" => "Gamithromycin", "cat_code" => "VETT", "mfg_code" => "ZJGUOBANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Azithromycin", "cat_code" => "VETT", "mfg_code" => "GUOLONG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Iron Dextran 20%", "cat_code" => "VETT", "mfg_code" => "VICTOR", "packing_code" => '30kg/thùng'],
                ["product_name" => "Neomycin Sulfate", "cat_code" => "VETT", "mfg_code" => "LIFECOME", "packing_code" => '20bou/thùng'],
                ["product_name" => "Neomycin Sulfate", "cat_code" => "VETT", "mfg_code" => "QILU", "packing_code" => '25kg/thùng'],
                ["product_name" => "Oxytetracycline Hcl (Otc) - 5Kg/Bag, 5Bag/Drum", "cat_code" => "VETT", "mfg_code" => "DAFENG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Glutaraldehyde 50% Pharma Grade", "cat_code" => "VETT", "mfg_code" => "SHENGLING", "packing_code" => '220kg/phuy'],
                ["product_name" => "Ampicillin Trihydrate", "cat_code" => "VETT", "mfg_code" => "UNITED", "packing_code" => '25kg/thùng'],
                ["product_name" => "Fipronil 97% Tc", "cat_code" => "VETT", "mfg_code" => "VISION", "packing_code" => '25kg/thùng'],
                ["product_name" => "Dihydrostreptomycin Sulfate Ep5", "cat_code" => "VETT", "mfg_code" => "SHENGXUE", "packing_code" => '5bou/túi'],
                ["product_name" => "Streptomycin Sulphate Oral", "cat_code" => "VETT", "mfg_code" => "SHENGXUE", "packing_code" => '20bou/thùng'],
                ["product_name" => "Tylvalosin Tartrate", "cat_code" => "VETT", "mfg_code" => "TAIYICIN", "packing_code" => '15kg/thùng'],
                ["product_name" => "Tilmicosin Phosphate", "cat_code" => "VETT", "mfg_code" => "QILUINNER", "packing_code" => '15kg/thùng'],
                ["product_name" => "Metamizole Sodium (Analgin)", "cat_code" => "VETT", "mfg_code" => "JIHENG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Dexamethasone Acetate", "cat_code" => "VETT", "mfg_code" => "RUIJIN", "packing_code" => '1kg/thùng'],
                ["product_name" => "Fosfomycin Sodium", "cat_code" => "VETT", "mfg_code" => "CATHAYONE", "packing_code" => '20kg/thùng'],
                ["product_name" => "Colistin Sulfate", "cat_code" => "VETT", "mfg_code" => "LIVZON", "packing_code" => '20kg/thùng'],
                ["product_name" => "Flunixin Meglumine", "cat_code" => "VETT", "mfg_code" => "NGL", "packing_code" => '100g/túi'],
                ["product_name" => "Diminazene Diaceturate", "cat_code" => "VETT", "mfg_code" => "NGL", "packing_code" => '100g/túi'],
                ["product_name" => "Imidocarb Dipropionate", "cat_code" => "VETT", "mfg_code" => "NGL", "packing_code" => '100g/túi'],
                ["product_name" => "Praziquantel", "cat_code" => "VETT", "mfg_code" => "NGL", "packing_code" => '100g/túi'],
                ["product_name" => "Toltrazuril", "cat_code" => "VETT", "mfg_code" => "NGL", "packing_code" => '100g/túi'],
                ["product_name" => "Maduramicin Ammonium", "cat_code" => "VETT", "mfg_code" => "QILUKP", "packing_code" => '25kg/thùng'],
                ["product_name" => "Fluconazole Usp", "cat_code" => "VETT", "mfg_code" => "SYNERGENE", "packing_code" => '50g/túi'],
                ["product_name" => "Flunixin Meglumine", "cat_code" => "VETT", "mfg_code" => "JIULONG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Penicillin G Procaine", "cat_code" => "VETT", "mfg_code" => "DONGFENG", "packing_code" => '20bou/thùng'],
                ["product_name" => "Sulfadimethoxine Sodium", "cat_code" => "VETT", "mfg_code" => "HUIHUANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Itraconazole (Micronized)", "cat_code" => "VETT", "mfg_code" => "SMILAX", "packing_code" => '25kg/thùng'],
                ["product_name" => "Gentamicin Sulphate Bp2002/Ep4 Microbial Limit", "cat_code" => "VETT", "mfg_code" => "FUAN", "packing_code" => '10bou/thùng'],
                ["product_name" => "Fosfomycin Sodium", "cat_code" => "VETT", "mfg_code" => "FAMASINO", "packing_code" => '20kg/thùng'],
                ["product_name" => "Tulathromycin", "cat_code" => "VETT", "mfg_code" => "LUKANG", "packing_code" => '4kg/thùng'],
                ["product_name" => "Clorsulon", "cat_code" => "VETT", "mfg_code" => "NGL", "packing_code" => '25kg/thùng'],
                ["product_name" => "Fenbendazole", "cat_code" => "VETT", "mfg_code" => "BAOZONG", "packing_code" => '20kg/thùng'],
                ["product_name" => "Tilmicosin Phosphate", "cat_code" => "VETT", "mfg_code" => "TAIYICIN", "packing_code" => '15kg/thùng'],
                ["product_name" => "Amprolium Hcl", "cat_code" => "VETT", "mfg_code" => "DAYANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Butaphosphan", "cat_code" => "VETT", "mfg_code" => "FST", "packing_code" => '25kg/thùng'],
                ["product_name" => "Levamisole Hydrochloride", "cat_code" => "VETT", "mfg_code" => "GUILIN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Tylvalosin Tartrate", "cat_code" => "VETT", "mfg_code" => "HVSEN", "packing_code" => '15kg/thùng'],
                ["product_name" => "Dodecyl Dimethyl Benzyl Ammonium Chloride (Benzalkonium Chloride) (Ddbac/Bkc) 80%", "cat_code" => "VETT", "mfg_code" => "KAIRUI-WATER", "packing_code" => '200kg/phuy'],
                ["product_name" => "Oxytetracycline Hcl (Otc)", "cat_code" => "VETT", "mfg_code" => "DAFENG", "packing_code" => '25kg/bao'],
                ["product_name" => "Amoxicillin And Clavulanate Potassium (4:1)", "cat_code" => "VETT", "mfg_code" => "UNITED", "packing_code" => '15.4kg/thùng'],
                ["product_name" => "Doxycycline Hyclate", "cat_code" => "VETT", "mfg_code" => "SDGUOBANG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Toltrazuril", "cat_code" => "VETT", "mfg_code" => "LINGYUN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Iron Dextran Solution 20%", "cat_code" => "VETT", "mfg_code" => "VICTOR", "packing_code" => '30kg/can'],
                ["product_name" => "Buparvaquone", "cat_code" => "VETT", "mfg_code" => "AMGIS", "packing_code" => '1kg/thùng'],
                ["product_name" => "Lincomycin Hydrochloride Usp/ Ih", "cat_code" => "VETT", "mfg_code" => "TOPFOND", "packing_code" => '25kg/thùng'],
                ["product_name" => "Doxycycline Hyclate 99%", "cat_code" => "VETT", "mfg_code" => "KUNSHAN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Florfenicol Cvp", "cat_code" => "VETT", "mfg_code" => "HISOAR", "packing_code" => '25kg/thùng'],
                ["product_name" => "Amoxicillin Trihydrate Micronized", "cat_code" => "VETT", "mfg_code" => "LVYUAN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Levamisole Hydrochloride Bp/Ip", "cat_code" => "VETT", "mfg_code" => "WHITEWHALE", "packing_code" => '25kg/thùng'],
                ["product_name" => "Florfenicol", "cat_code" => "VETT", "mfg_code" => "JINGSHAN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Streptomycin Sulphate Sterile 5Bou * Tin, 2 Tin * Carton Ep", "cat_code" => "VETT", "mfg_code" => "SHENGXUE", "packing_code" => '5bou/túi'],
                ["product_name" => "Analgin Ep", "cat_code" => "VETT", "mfg_code" => "HAISEN", "packing_code" => '25kg/thùng'],
                ["product_name" => "Azithromycin Dihydrate Usp", "cat_code" => "VETT", "mfg_code" => "HEBEI-DONGFENG", "packing_code" => '25kg/thùng'],
                ["product_name" => "Neomycin Sulphate Usp", "cat_code" => "VETT", "mfg_code" => "SANXIA-HUBEI", "packing_code" => '20bou/thùng'],
                ["product_name" => "Diminazene Diaceturate", "cat_code" => "VETT", "mfg_code" => "YUWAN", "packing_code" => '1kg/túi'],
                ["product_name" => "Sulbactam Sodium Sterile Usp", "cat_code" => "VETT", "mfg_code" => "RUIYING", "packing_code" => '1kg/túi'],
            ];
            $mfgMap = \App\Models\Contact::whereIn('contact_code', array_column($products, 'mfg_code'))
                ->pluck('id', 'contact_code');

            $catMap = \App\Models\Category::whereIn('category_code', array_column($products, 'cat_code'))
                ->pluck('id', 'category_code');

            $packMap = \App\Models\Packing::whereIn('packing_name', array_column($products, 'packing_code'))
                ->pluck('id', 'packing_name');

            foreach ($products as $product) {
                \App\Models\Product::create([
                    'product_name' => $product['product_name'],
                    'is_active' => true,
                    'mfg_id' => $mfgMap[$product['mfg_code']] ?? null,
                    'category_id' => $catMap[$product['cat_code']] ?? null,
                    'packing_id' => $packMap[$product['packing_code']] ?? null,
                    'product_life_cycle' => 365,
                ])
                    ->setProductCode()
                    ->setUnitLabel()
                    ->setFullName();
            }
            $this->command->info('Products seeded!');
        });
    }
}
